---
Description: Setup an Amazon Linux Web Server
Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      SecurityGroups:
      - !Ref WebserverSecurityGroup
      Tags:
      - Key: Name 
        Value: Amazon Linux Web Server
      UserData:
        'Fn::Base64': |
          #!/bin/bash
          set -x
          #skip prompts
          export DEBIAN_FRONTEND = noninteractive
          #set timezone
          timedatactl set-timezone America/New_York
          #install and setup apache
          yum install -y httpd
          cd /var/www/html
          echo "<h1>Shruthi's Amazon Linux Cloud Formation Server</h1>" > index.html
          service httpd start    
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allows HTTP
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp